name: Update and Deploy

on:
  schedule:
    - cron: "15 6 * * *"
      timezone: "America/Argentina/Buenos_Aires"

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Test Santander connection
        run: |
          curl -v \
            --max-time 20 \
            -H "Accept: application/json" \
            -H "User-Agent: Mozilla/5.0" \
            "https://www.santander.com.ar/bff-benefits/brands?categories=GAS&days=&exclusive=&pay_with=&location=caba&page=1&limit=12"

      - name: Collect benefits
        run: npm start

      - name: Filter active benefits
        run: npm run filter-active

      - name: Generate HTML
        run: npm run build-html

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./output

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4