name: Update and Deploy

on:
  schedule:
    - cron: "15 6 * * *"
      timezone: "America/Argentina/Buenos_Aires"

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Diagnose Santander API
        run: |
          echo "=== API IPv4 ==="

          curl -4 -v \
            --http1.1 \
            --max-time 20 \
            -o /dev/null \
            -w "\nHTTP: %{http_code}\nIP: %{remote_ip}\nTime: %{time_total}\n" \
            "https://www.santander.com.ar/bff-benefits/brands?categories=GAS&days=&exclusive=&pay_with=&location=caba&page=1&limit=12"

          echo "=== API IPv6 ==="

          curl -6 -v \
            --http1.1 \
            --max-time 20 \
            -o /dev/null \
            -w "\nHTTP: %{http_code}\nIP: %{remote_ip}\nTime: %{time_total}\n" \
            "https://www.santander.com.ar/bff-benefits/brands?categories=GAS&days=&exclusive=&pay_with=&location=caba&page=1&limit=12"

      - name: Test Santander connection
        run: |
          curl -v \
            --http1.1 \
            --max-time 20 \
            -c /tmp/santander-cookies.txt \
            -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36" \
            "https://www.santander.com.ar/" \
            -o /dev/null

          echo "=== Cookies obtenidas ==="
          cat /tmp/santander-cookies.txt

          echo "=== Llamando API ==="

          curl -v \
            --http1.1 \
            --max-time 20 \
            -b /tmp/santander-cookies.txt \
            -H "Accept: application/json, text/plain, */*" \
            -H "Accept-Language: es-AR,es;q=0.9,en;q=0.8" \
            -H "Referer: https://www.santander.com.ar/" \
            -H "Origin: https://www.santander.com.ar" \
            -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36" \
            "https://www.santander.com.ar/bff-benefits/brands?categories=GAS&days=&exclusive=&pay_with=&location=caba&page=1&limit=12"

      - name: Collect benefits
        run: npm start

      - name: Filter active benefits
        run: npm run filter-active

      - name: Generate HTML
        run: npm run build-html

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./output

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4